module.exports = function (grunt) {
	grunt.config('ipsum.images', {
		dest : 'test/actual/images.json',
		template : {
			niceNice                : '{%= ipsum.niceNice %}',
			niceNiceMustang         : '{%= ipsum.niceNiceMustang %}',
			fillMurray              : '{%= ipsum.fillMurray %}',
			fillMurrayBw            : '{%= ipsum.fillMurrayBw %}',
			placeCage               : '{%= ipsum.placeCage %}',
			placeCageBw             : '{%= ipsum.placeCageBw %}',
			placeCageCrazy          : '{%= ipsum.placeCageCrazy %}',
			placeBear               : '{%= ipsum.placeBear %}',
			placeBearBw             : '{%= ipsum.placeBearBw %}',
			placeDog                : '{%= ipsum.placeDog %}',
			placeDogBw              : '{%= ipsum.placeDogBw %}',
			placeKitten             : '{%= ipsum.placeKitten %}',
			placeKittenBw           : '{%= ipsum.placeKittenBw %}',
			placeZombie             : '{%= ipsum.placeZombie %}',
			placeZombieBw           : '{%= ipsum.placeZombieBw %}',
			placeSheen              : '{%= ipsum.placeSheen %}',
			baconMockup             : '{%= ipsum.baconMockup %}',
			loremPixel              : '{%= ipsum.loremPixel %}',
			loremPixelAbstract      : '{%= ipsum.loremPixelAbstract %}',
			loremPixelAnimals       : '{%= ipsum.loremPixelAnimals %}',
			loremPixelBusiness      : '{%= ipsum.loremPixelBusiness %}',
			loremPixelCats          : '{%= ipsum.loremPixelCats %}',
			loremPixelCity          : '{%= ipsum.loremPixelCity %}',
			loremPixelFood          : '{%= ipsum.loremPixelFood %}',
			loremPixelNightlife     : '{%= ipsum.loremPixelNightlife %}',
			loremPixelFashion       : '{%= ipsum.loremPixelFashion %}',
			loremPixelPeople        : '{%= ipsum.loremPixelPeople %}',
			loremPixelNature        : '{%= ipsum.loremPixelNature %}',
			loremPixelSports        : '{%= ipsum.loremPixelSports %}',
			loremPixelTechnics      : '{%= ipsum.loremPixelTechnics %}',
			loremPixelTransport     : '{%= ipsum.loremPixelTransport %}',
			loremPixelBw            : '{%= ipsum.loremPixelBw %}',
			loremPixelAbstractBw    : '{%= ipsum.loremPixelAbstractBw %}',
			loremPixelAnimalsBw     : '{%= ipsum.loremPixelAnimalsBw %}',
			loremPixelBusinessBw    : '{%= ipsum.loremPixelBusinessBw %}',
			loremPixelCatsBw        : '{%= ipsum.loremPixelCatsBw %}',
			loremPixelCityBw        : '{%= ipsum.loremPixelCityBw %}',
			loremPixelFoodBw        : '{%= ipsum.loremPixelFoodBw %}',
			loremPixelNightlifeBw   : '{%= ipsum.loremPixelNightlifeBw %}',
			loremPixelFashionBw     : '{%= ipsum.loremPixelFashionBw %}',
			loremPixelPeopleBw      : '{%= ipsum.loremPixelPeopleBw %}',
			loremPixelNatureBw      : '{%= ipsum.loremPixelNatureBw %}',
			loremPixelSportsBw      : '{%= ipsum.loremPixelSportsBw %}',
			loremPixelTechnicsBw    : '{%= ipsum.loremPixelTechnicsBw %}',
			loremPixelTransportBw   : '{%= ipsum.loremPixelTransportBw %}',
		}
	});
	grunt.config('ipsum.images-20-40', {
		dest : 'test/actual/images-20-40.json',
		template : {
			niceNice                : '{%= ipsum.niceNice(20, 40) %}',
			niceNiceMustang         : '{%= ipsum.niceNiceMustang(20, 40) %}',
			fillMurray              : '{%= ipsum.fillMurray(20, 40) %}',
			fillMurrayBw            : '{%= ipsum.fillMurrayBw(20, 40) %}',
			placeCage               : '{%= ipsum.placeCage(20, 40) %}',
			placeCageBw             : '{%= ipsum.placeCageBw(20, 40) %}',
			placeCageCrazy          : '{%= ipsum.placeCageCrazy(20, 40) %}',
			placeBear               : '{%= ipsum.placeBear(20, 40) %}',
			placeBearBw             : '{%= ipsum.placeBearBw(20, 40) %}',
			placeDog                : '{%= ipsum.placeDog(20, 40) %}',
			placeDogBw              : '{%= ipsum.placeDogBw(20, 40) %}',
			placeKitten             : '{%= ipsum.placeKitten(20, 40) %}',
			placeKittenBw           : '{%= ipsum.placeKittenBw(20, 40) %}',
			placeZombie             : '{%= ipsum.placeZombie(20, 40) %}',
			placeZombieBw           : '{%= ipsum.placeZombieBw(20, 40) %}',
			placeSheen              : '{%= ipsum.placeSheen(20, 40) %}',
			baconMockup             : '{%= ipsum.baconMockup(20, 40) %}',
			loremPixel              : '{%= ipsum.loremPixel(20, 40) %}',
			loremPixelAbstract      : '{%= ipsum.loremPixelAbstract(20, 40) %}',
			loremPixelAnimals       : '{%= ipsum.loremPixelAnimals(20, 40) %}',
			loremPixelBusiness      : '{%= ipsum.loremPixelBusiness(20, 40) %}',
			loremPixelCats          : '{%= ipsum.loremPixelCats(20, 40) %}',
			loremPixelCity          : '{%= ipsum.loremPixelCity(20, 40) %}',
			loremPixelFood          : '{%= ipsum.loremPixelFood(20, 40) %}',
			loremPixelNightlife     : '{%= ipsum.loremPixelNightlife(20, 40) %}',
			loremPixelFashion       : '{%= ipsum.loremPixelFashion(20, 40) %}',
			loremPixelPeople        : '{%= ipsum.loremPixelPeople(20, 40) %}',
			loremPixelNature        : '{%= ipsum.loremPixelNature(20, 40) %}',
			loremPixelSports        : '{%= ipsum.loremPixelSports(20, 40) %}',
			loremPixelTechnics      : '{%= ipsum.loremPixelTechnics(20, 40) %}',
			loremPixelTransport     : '{%= ipsum.loremPixelTransport(20, 40) %}',
			loremPixelBw            : '{%= ipsum.loremPixelBw(20, 40) %}',
			loremPixelAbstractBw    : '{%= ipsum.loremPixelAbstractBw(20, 40) %}',
			loremPixelAnimalsBw     : '{%= ipsum.loremPixelAnimalsBw(20, 40) %}',
			loremPixelBusinessBw    : '{%= ipsum.loremPixelBusinessBw(20, 40) %}',
			loremPixelCatsBw        : '{%= ipsum.loremPixelCatsBw(20, 40) %}',
			loremPixelCityBw        : '{%= ipsum.loremPixelCityBw(20, 40) %}',
			loremPixelFoodBw        : '{%= ipsum.loremPixelFoodBw(20, 40) %}',
			loremPixelNightlifeBw   : '{%= ipsum.loremPixelNightlifeBw(20, 40) %}',
			loremPixelFashionBw     : '{%= ipsum.loremPixelFashionBw(20, 40) %}',
			loremPixelPeopleBw      : '{%= ipsum.loremPixelPeopleBw(20, 40) %}',
			loremPixelNatureBw      : '{%= ipsum.loremPixelNatureBw(20, 40) %}',
			loremPixelSportsBw      : '{%= ipsum.loremPixelSportsBw(20, 40) %}',
			loremPixelTechnicsBw    : '{%= ipsum.loremPixelTechnicsBw(20, 40) %}',
			loremPixelTransportBw   : '{%= ipsum.loremPixelTransportBw(20, 40) %}',
		}
	});
	grunt.config('ipsum.images-random-35', {
		dest : 'test/actual/images-random-35.json',
		template : {
			niceNice                : '{%= ipsum.niceNice([10,20], 35) %}',
			niceNiceMustang         : '{%= ipsum.niceNiceMustang([10,20], 35) %}',
			fillMurray              : '{%= ipsum.fillMurray([10,20], 35) %}',
			fillMurrayBw            : '{%= ipsum.fillMurrayBw([10,20], 35) %}',
			placeCage               : '{%= ipsum.placeCage([10,20], 35) %}',
			placeCageBw             : '{%= ipsum.placeCageBw([10,20], 35) %}',
			placeCageCrazy          : '{%= ipsum.placeCageCrazy([10,20], 35) %}',
			placeBear               : '{%= ipsum.placeBear([10,20], 35) %}',
			placeBearBw             : '{%= ipsum.placeBearBw([10,20], 35) %}',
			placeDog                : '{%= ipsum.placeDog([10,20], 35) %}',
			placeDogBw              : '{%= ipsum.placeDogBw([10,20], 35) %}',
			placeKitten             : '{%= ipsum.placeKitten([10,20], 35) %}',
			placeKittenBw           : '{%= ipsum.placeKittenBw([10,20], 35) %}',
			placeZombie             : '{%= ipsum.placeZombie([10,20], 35) %}',
			placeZombieBw           : '{%= ipsum.placeZombieBw([10,20], 35) %}',
			placeSheen              : '{%= ipsum.placeSheen([10,20], 35) %}',
			baconMockup             : '{%= ipsum.baconMockup([10,20], 35) %}',
			loremPixel              : '{%= ipsum.loremPixel([10,20], 35) %}',
			loremPixelAbstract      : '{%= ipsum.loremPixelAbstract([10,20], 35) %}',
			loremPixelAnimals       : '{%= ipsum.loremPixelAnimals([10,20], 35) %}',
			loremPixelBusiness      : '{%= ipsum.loremPixelBusiness([10,20], 35) %}',
			loremPixelCats          : '{%= ipsum.loremPixelCats([10,20], 35) %}',
			loremPixelCity          : '{%= ipsum.loremPixelCity([10,20], 35) %}',
			loremPixelFood          : '{%= ipsum.loremPixelFood([10,20], 35) %}',
			loremPixelNightlife     : '{%= ipsum.loremPixelNightlife([10,20], 35) %}',
			loremPixelFashion       : '{%= ipsum.loremPixelFashion([10,20], 35) %}',
			loremPixelPeople        : '{%= ipsum.loremPixelPeople([10,20], 35) %}',
			loremPixelNature        : '{%= ipsum.loremPixelNature([10,20], 35) %}',
			loremPixelSports        : '{%= ipsum.loremPixelSports([10,20], 35) %}',
			loremPixelTechnics      : '{%= ipsum.loremPixelTechnics([10,20], 35) %}',
			loremPixelTransport     : '{%= ipsum.loremPixelTransport([10,20], 35) %}',
			loremPixelBw            : '{%= ipsum.loremPixelBw([10,20], 35) %}',
			loremPixelAbstractBw    : '{%= ipsum.loremPixelAbstractBw([10,20], 35) %}',
			loremPixelAnimalsBw     : '{%= ipsum.loremPixelAnimalsBw([10,20], 35) %}',
			loremPixelBusinessBw    : '{%= ipsum.loremPixelBusinessBw([10,20], 35) %}',
			loremPixelCatsBw        : '{%= ipsum.loremPixelCatsBw([10,20], 35) %}',
			loremPixelCityBw        : '{%= ipsum.loremPixelCityBw([10,20], 35) %}',
			loremPixelFoodBw        : '{%= ipsum.loremPixelFoodBw([10,20], 35) %}',
			loremPixelNightlifeBw   : '{%= ipsum.loremPixelNightlifeBw([10,20], 35) %}',
			loremPixelFashionBw     : '{%= ipsum.loremPixelFashionBw([10,20], 35) %}',
			loremPixelPeopleBw      : '{%= ipsum.loremPixelPeopleBw([10,20], 35) %}',
			loremPixelNatureBw      : '{%= ipsum.loremPixelNatureBw([10,20], 35) %}',
			loremPixelSportsBw      : '{%= ipsum.loremPixelSportsBw([10,20], 35) %}',
			loremPixelTechnicsBw    : '{%= ipsum.loremPixelTechnicsBw([10,20], 35) %}',
			loremPixelTransportBw   : '{%= ipsum.loremPixelTransportBw([10,20], 35) %}',
		}
	});
	grunt.config('ipsum.images-random', {
		dest : 'test/actual/images-random.json',
		template : {
			niceNice                : '{%= ipsum.niceNice([300,400], [50,80]) %}',
			niceNiceMustang         : '{%= ipsum.niceNiceMustang([300,400], [50,80]) %}',
			fillMurray              : '{%= ipsum.fillMurray([300,400], [50,80]) %}',
			fillMurrayBw            : '{%= ipsum.fillMurrayBw([300,400], [50,80]) %}',
			placeCage               : '{%= ipsum.placeCage([300,400], [50,80]) %}',
			placeCageBw             : '{%= ipsum.placeCageBw([300,400], [50,80]) %}',
			placeCageCrazy          : '{%= ipsum.placeCageCrazy([300,400], [50,80]) %}',
			placeBear               : '{%= ipsum.placeBear([300,400], [50,80]) %}',
			placeBearBw             : '{%= ipsum.placeBearBw([300,400], [50,80]) %}',
			placeDog                : '{%= ipsum.placeDog([300,400], [50,80]) %}',
			placeDogBw              : '{%= ipsum.placeDogBw([300,400], [50,80]) %}',
			placeKitten             : '{%= ipsum.placeKitten([300,400], [50,80]) %}',
			placeKittenBw           : '{%= ipsum.placeKittenBw([300,400], [50,80]) %}',
			placeZombie             : '{%= ipsum.placeZombie([300,400], [50,80]) %}',
			placeZombieBw           : '{%= ipsum.placeZombieBw([300,400], [50,80]) %}',
			placeSheen              : '{%= ipsum.placeSheen([300,400], [50,80]) %}',
			baconMockup             : '{%= ipsum.baconMockup([300,400], [50,80]) %}',
			loremPixel              : '{%= ipsum.loremPixel([300,400], [50,80]) %}',
			loremPixelAbstract      : '{%= ipsum.loremPixelAbstract([300,400], [50,80]) %}',
			loremPixelAnimals       : '{%= ipsum.loremPixelAnimals([300,400], [50,80]) %}',
			loremPixelBusiness      : '{%= ipsum.loremPixelBusiness([300,400], [50,80]) %}',
			loremPixelCats          : '{%= ipsum.loremPixelCats([300,400], [50,80]) %}',
			loremPixelCity          : '{%= ipsum.loremPixelCity([300,400], [50,80]) %}',
			loremPixelFood          : '{%= ipsum.loremPixelFood([300,400], [50,80]) %}',
			loremPixelNightlife     : '{%= ipsum.loremPixelNightlife([300,400], [50,80]) %}',
			loremPixelFashion       : '{%= ipsum.loremPixelFashion([300,400], [50,80]) %}',
			loremPixelPeople        : '{%= ipsum.loremPixelPeople([300,400], [50,80]) %}',
			loremPixelNature        : '{%= ipsum.loremPixelNature([300,400], [50,80]) %}',
			loremPixelSports        : '{%= ipsum.loremPixelSports([300,400], [50,80]) %}',
			loremPixelTechnics      : '{%= ipsum.loremPixelTechnics([300,400], [50,80]) %}',
			loremPixelTransport     : '{%= ipsum.loremPixelTransport([300,400], [50,80]) %}',
			loremPixelBw            : '{%= ipsum.loremPixelBw([300,400], [50,80]) %}',
			loremPixelAbstractBw    : '{%= ipsum.loremPixelAbstractBw([300,400], [50,80]) %}',
			loremPixelAnimalsBw     : '{%= ipsum.loremPixelAnimalsBw([300,400], [50,80]) %}',
			loremPixelBusinessBw    : '{%= ipsum.loremPixelBusinessBw([300,400], [50,80]) %}',
			loremPixelCatsBw        : '{%= ipsum.loremPixelCatsBw([300,400], [50,80]) %}',
			loremPixelCityBw        : '{%= ipsum.loremPixelCityBw([300,400], [50,80]) %}',
			loremPixelFoodBw        : '{%= ipsum.loremPixelFoodBw([300,400], [50,80]) %}',
			loremPixelNightlifeBw   : '{%= ipsum.loremPixelNightlifeBw([300,400], [50,80]) %}',
			loremPixelFashionBw     : '{%= ipsum.loremPixelFashionBw([300,400], [50,80]) %}',
			loremPixelPeopleBw      : '{%= ipsum.loremPixelPeopleBw([300,400], [50,80]) %}',
			loremPixelNatureBw      : '{%= ipsum.loremPixelNatureBw([300,400], [50,80]) %}',
			loremPixelSportsBw      : '{%= ipsum.loremPixelSportsBw([300,400], [50,80]) %}',
			loremPixelTechnicsBw    : '{%= ipsum.loremPixelTechnicsBw([300,400], [50,80]) %}',
			loremPixelTransportBw   : '{%= ipsum.loremPixelTransportBw([300,400], [50,80]) %}',
		}
	});
};
